language: R
r:
  - devel
  - "3.4"
  - "3.3"

os:
  - linux
  - osx

sudo: false
cache: packages
warnings_are_errors: true

r_packages:
  - covr

services:
  - mongodb

before_script:
  - bash tests/ci_env_setup
  - bash tests/download_datasets

after_success:
  - Rscript -e 'covr::coveralls()'